# Bio311

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(cluster)
library(gplots)
library(ggplot2)
library(RColorBrewer)
library(dplyr)
library(tidyr)
library(stringr)
library(dendextend)
library(gProfileR)
library(org.Sc.sgd.db)
library(data.table)
library(igraph)

color.scheme <- rev(brewer.pal(8, "RdBu"))
```

## Data Processing
```{r expression data, echo=FALSE, warning=FALSE}
huebert_expr <- read.csv("huebert-2012-expression.csv", 
                         stringsAsFactors = FALSE, 
                         fileEncoding = "latin1")

# filter out noncoding (or unspecified) genes
huebert_expr_coding <- huebert_expr[huebert_expr$coding.noncoding == "coding",]

# transpose and convert matrix to data frame
huebert_expmt <- huebert_expr_coding[, 7:28] %>% sapply(as.numeric) %>% 
  t() %>% as.data.frame()

# use this for correlation matrix (no time column)
colnames(huebert_expmt) <- huebert_expr_coding$ID

# remove genes with NA's
huebert_expmt <- huebert_expmt[, apply(huebert_expmt, 2, function(x) !any(is.na(x)))]

# average repeated observations at 30 minutes for both conditions
huebert_expmt[6, ] <- apply(huebert_expmt, 2, function(x) mean(c(x[6], x[9:11]), na.rm = TRUE))
huebert_expmt[17, ] <- apply(huebert_expmt, 2, function(x) mean(c(x[17], x[20:22]), na.rm = TRUE))
huebert_expmt <- huebert_expmt[-c(9:11, 20:22), ]

# add the experiment condition and time columns
huebert_expmt2 <- huebert_expmt
huebert_expmt2$expt <- c(rep("wildtype", 8), rep("msn24", 8))
huebert_expmt2$time <- rownames(huebert_expmt) %>% strsplit("[.T]") %>% 
  sapply(function(x) as.numeric(x[4]))

# reorder
huebert_expmt2 <- huebert_expmt2[,c(5614:5615, 1:5613)]

# transform the data set to a long form
huebert_long <- gather(huebert_expmt2, gene, expression, -time, -expt)
```

```{r TF binding data, echo=FALSE}
huebert_TF <- read.csv("huebert-2012-TFbinding-annotated.csv", 
                       stringsAsFactors = FALSE)
```

## Hierarchical Clustering
```{r hier_cluster, warning=FALSE}
huebert.cor <- huebert_expmt %>% cor(use = "pairwise.complete.obs")
huebert.dist <- as.dist(1 - huebert.cor)
#huebert.cor[is.na(huebert.cor)] <- -1  # assume all NA's in correlation matrix is -1
huebert.clust <- hclust(huebert.dist, method = "complete")
huebert.dend <- as.dendrogram(huebert.clust)

color.dend <- color_branches(huebert.dend, h = 1.8, col = brewer.pal(8, "Dark2"))
plot(color.dend, leaflab = "none")
```

```{r cluster_info, warning=FALSE}
hclusters <- cutree(huebert.dend, h = 1.8, order_clusters_as_data = FALSE)
hclusters.df <- data.frame(gene = names(hclusters), cluster = hclusters, 
                           stringsAsFactors = FALSE)

# save the names of genes in each cluster
hclusters.genes <- list()
for (i in 1:9) {
  hclusters.genes[[i]] <- filter(hclusters.df, cluster == i)$gene
}
```

## Correlation Heatmap
```{r corr_heatmap, warning=FALSE}
heatmap.2(huebert.cor, 
          Rowv = ladderize(huebert.dend), 
          Colv = ladderize(huebert.dend), 
          dendrogram = "both", 
          revC = TRUE,  # rev column order of dendrogram so conforms to natural representation
          trace = "none", 
          density.info = "none",
          col = color.scheme, key = FALSE,
          labRow = FALSE, labCol = FALSE)
```

## K-medoids Clustering
```{r k_clust, warning=FALSE}
huebert.kmedoids <- pam(huebert.dist, 9)  # create k-medoids clustering with 9 clusters
huebert.kclusters <- huebert.kmedoids$cluster

# save the names of genes in each cluster
kclusters.genes <- list()
for (i in 1:9) {
  kclusters.genes[[i]] <- names(huebert.kclusters[huebert.kclusters == i])
}
```

```{r corr_heatmap_k}
# reorder correlation matrix by the ordering given by clustering
huebert.kmedoids.cor <- huebert.cor[order(huebert.kclusters), order(huebert.kclusters)]

heatmap.2(huebert.kmedoids.cor, Rowv = NULL, Colv = NULL, 
          dendrogram = "none", 
          trace = "none", density.info = "none",
          col = color.scheme, key = FALSE,
          labRow = FALSE, labCol = FALSE)
```

## Expression Heatmap
```{r cluster dynamic, fig.height=15, fig.width=5}
huebert_long %>% 
  filter(gene %in% hclusters.genes[[1]] & expt == "msn24") %>% 
  ggplot(aes(x = factor(time), y = gene)) + 
    geom_tile(aes(fill = expression)) + 
    scale_fill_gradientn(colors = color.scheme, limits = c(-4, 4)) + 
    ggtitle("Msn2/4 Double Deletion, Hierarchical Cluster 1") + 
    xlab("time") + 
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

huebert_long %>% 
  filter(gene %in% kclusters.genes[[1]] & expt == "msn24") %>% 
  ggplot(aes(x = factor(time), y = gene)) + 
    geom_tile(aes(fill = expression)) + 
    scale_fill_gradientn(colors = color.scheme, limits = c(-4, 4)) + 
    ggtitle("Msn2/4 Double Deletion, K-medoids Cluster 1") + 
    xlab("time") + 
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

```{r cluster dynamic, fig.height=15, fig.width=5}
samph <- sample(kclusters.genes[[1]], 150)
sampk <- sample(kclusters.genes[[1]], 150)

huebert_long %>% 
  filter(gene %in% samph & expt == "wildtype") %>% 
  ggplot(aes(x = factor(time), y = gene)) + 
    geom_tile(aes(fill = expression)) + 
    scale_fill_gradientn(colors = color.scheme, limits = c(-4, 4)) + 
    ggtitle("Wild Type, Hierarchical Cluster 1") + 
    xlab("time") + 
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())

huebert_long %>% 
  filter(gene %in% sampk & expt == "wildtype") %>% 
  ggplot(aes(x = factor(time), y = gene)) + 
    geom_tile(aes(fill = expression)) + 
    scale_fill_gradientn(colors = color.scheme, limits = c(-4, 4)) + 
    ggtitle("Wild Type, K-medoids Cluster 1") + 
    xlab("time") + 
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank())
```

## TF binding
```{r trans_binding_data}
huebert_TF <- read.csv("huebert-2012-TFbinding-annotated.csv", 
                       stringsAsFactors = FALSE)
huebert.tfs <- huebert_TF %>% 
  dplyr::select(-(Gene.Symbol:PeakID)) %>% 
  dplyr::rename(ID = Gene.ID)
```

```{r harbison TF binding data, echo=FALSE}
harbison_TF <- fread("harbison-2004-TFbinding-other.txt")
class(harbison_TF) <- "data.frame"
harbison_tfs <- harbison_TF %>% 
  dplyr::rename(ID = V1, Name = V2, GO = V3)

huebert_expr <- read.csv("huebert-2012-expression.csv", 
                         stringsAsFactors = FALSE, 
                         fileEncoding = "latin1")
huebert_expr_subset <- semi_join(huebert_expr, harbison_tfs) %>% 
  dplyr::select(ID, contains("T30"))
huebert_expr_subset_genes <- huebert_expr_subset$ID
huebert_expr_subset <- huebert_expr_subset %>% dplyr::select(-1)
huebert_expr_subset <- apply(huebert_expr_subset, 2, 
                             function(x) as.matrix(as.numeric(x))) %>% 
  as.data.frame()
rownames(huebert_expr_subset) <- huebert_expr_subset_genes

huebert_expr_subset <- huebert_expr_subset[apply(huebert_expr_subset, 1, 
                                                 function(x) !any(is.na(x))), ]

p_values <- apply(huebert_expr_subset, 1, 
                  function(x) t.test(x[1:4], x[5:8])$p.value)
genes_t <- sort(p_values) %>% .[1:200] %>% names()
```

```{r}
msn2_h2o2 <- harbison_tfs %>% dplyr::select(1:3, MSN2_H2O2Hi, MSN2_H2O2Lo) %>% 
  arrange(MSN2_H2O2Hi)

msn2_binding <- harbison_tfs %>% dplyr::filter(Name == "MSN2") %>% 
  dplyr::select(-(1:3)) %>% t() %>% as.data.frame() %>% 
  mutate(tf = rownames(.)) %>% dplyr::rename(pvalue = V1) %>% 
  filter(pvalue <= 1e-2)
msn4_binding <- harbison_tfs %>% dplyr::filter(Name == "MSN4")

#filtered based on genes_t
msn2_h2o2_sig_genes <- msn2_h2o2 %>% filter(ID %in% genes_t)

harbison_tfs_sig_genes <- harbison_tfs %>% filter(ID %in% genes_t) %>% dplyr::select(-Name, -GO) 

harbison.tfs.long <- harbison_tfs_sig_genes %>% 
  tidyr::gather(TF, pvalue, -ID) %>% # cast to long format
  dplyr::select(TF, ID, pvalue) # reorder columns

harbison.tfs.long.sig <- 
    harbison.tfs.long %>% 
    filter(pvalue < 0.05 & TF != "MSN2_H2O2Hi" & TF != "MSN2_H2O2Lo")
```

```{r clustering on the subset}
huebert_t <- huebert_expr %>% filter(ID %in% genes_t) %>% dplyr::select(-(2:6))
huebert_expmt_t <- huebert_t %>% dplyr::select(-1) %>% sapply(as.numeric) %>% 
  t() %>% as.data.frame()
colnames(huebert_expmt_t) <- huebert_t$ID

huebert_expmt_t[6, ] <- apply(huebert_expmt_t, 2, function(x) mean(c(x[6], x[9:11])))
huebert_expmt_t[17, ] <- apply(huebert_expmt_t, 2, function(x) mean(c(x[17], x[20:22])))
huebert_expmt_t <- huebert_expmt_t[-c(9:11, 20:22), ]

huebert_cor_t <- huebert_expmt_t %>% cor(use = "pairwise.complete.obs")
huebert_dist_t <- as.dist(1 - huebert_cor_t)
huebert_clust_t <- hclust(huebert_dist_t, method = "complete")
huebert_dend_t <- as.dendrogram(huebert_clust_t)

color_dend_t <- color_branches(huebert_dend_t, k = 5, 
                               col = brewer.pal(5, "Dark2"))

plot(color_dend_t, horiz = TRUE, leaflab = "none")

hclusters_t <- cutree(huebert_dend_t, k = 5, order_clusters_as_data = FALSE)
hclusters_df_t <- data.frame(gene = names(hclusters_t), cluster = hclusters_t, 
                             stringsAsFactors = FALSE)

hclusters_genes_t <- list()
for (i in 1:5) {
  hclusters_genes_t[[i]] <- filter(hclusters_df_t, cluster == i)$gene
}

profiles_t <- gprofiler(hclusters_genes_t[[5]], 
                        organism = "scerevisiae",
                        max_p_value = 0.05, 
                        src_filter = "GO:BP",
                        hier_filtering = "moderate")
profiles_t$term.name
```

```{r network}
harbison_tfs <- fread("harbison-2004-TFbinding-other.txt")
class(harbison_tfs) <- "data.frame"
harbison_tfs <- harbison_tfs %>% 
  dplyr::rename(ID = V1, Name = V2, GO = V3)

harbison_tfs_h2o2 <- harbison_tfs %>% dplyr::select(2, contains("H2O2Hi"))
harbison_tfs_h2o2 <- harbison_tfs_h2o2 %>% filter(Name != "#REF!") %>% unique()
rownames(harbison_tfs_h2o2) <- harbison_tfs_h2o2$Name
harbison_tfs_h2o2 <- harbison_tfs_h2o2[, -1]
colnames(harbison_tfs_h2o2) <- colnames(harbison_tfs_h2o2) %>% 
  as.data.frame() %>% apply(., 1, function(x) strsplit(x, c("_", " "))[[1]][1])

n_df <- data.frame(from, to)
for (i in 1:nrow(harbison_tfs_h2o2)) {
  for (j in 1:ncol(harbison_tfs_h2o2)) {
    if (harbison_tfs_h2o2[i, j] <= 0.00001 & !is.na(harbison_tfs_h2o2[i, j])) {
      n_df <- rbind(n_df, 
                    data.frame(from = colnames(harbison_tfs_h2o2)[j], 
                               to = rownames(harbison_tfs_h2o2)[i]))
    }
  }
}

g <- graph_from_data_frame(n_df)
l <- layout_nicely(g)
plot(g, layout = l, edge.arrow.size = .1, 
     vertex.shape = "none", vertex.label.cex = 0.5)
```

```{r}
msn2_genes_h2o2 <- harbison_tfs_h2o2 %>% dplyr::select(1:3, MSN2) %>% 
  arrange(MSN2)
n_df <- data.frame(from = rep("MSN2", 8), to = msn2_genes_h2o2$Name[1:8], 
                   stringsAsFactors = FALSE) %>% rbind(n_df)

tf_msn2_h2o2 <- harbison_tfs_h2o2 %>% filter(Name == "MSN2") %>% 
  dplyr::select(-(1:3)) %>% 
  t() %>% as.data.frame() %>% dplyr::rename(MSN2 = V1) %>% 
  mutate(TF = rownames(.)) %>% 
  arrange(MSN2)
n_df <- data.frame(from = tf_msn2_h2o2$TF[1:3], to = rep("MSN2", 3), 
                   stringsAsFactors = FALSE) %>% rbind(n_df)

```

```{r huebert_activation_repressing, echo=FALSE, warning=FALSE}
huebert_expr_time_subset <- semi_join(huebert_expr, huebert.tfs)
```
